// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30pBayIuGsnEO51sN2WjWDf2hbTVWAnA',
    appId: '1:697775337298:web:58b737294208fa418e548b',
    messagingSenderId: '697775337298',
    projectId: 'wedding-ca163',
    authDomain: 'wedding-ca163.firebaseapp.com',
    storageBucket: 'wedding-ca163.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKahfhTNm0hC3ls_ULflf7lQYOBPxcAI',
    appId: '1:697775337298:android:0bc3ff8fe440867a8e548b',
    messagingSenderId: '697775337298',
    projectId: 'wedding-ca163',
    storageBucket: 'wedding-ca163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Ry8TQxhhUemX7H0wIhJ34t7OazGps3Q',
    appId: '1:697775337298:ios:7b0b4039ed80dde68e548b',
    messagingSenderId: '697775337298',
    projectId: 'wedding-ca163',
    storageBucket: 'wedding-ca163.appspot.com',
    iosClientId: '697775337298-tf2vfm9pcqnijprsggnnu42nc81jmqh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedding',
  );
}
